# Generated by Django 5.2.15 on 2026-06-30 15:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('other_faculty', 'كلية أخرى'), ('central_admin', 'إدارة مركزية')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('direction', models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=15)),
                ('scope', models.CharField(choices=[('internal', 'داخلي'), ('inter_faculty', 'بين الكليات'), ('central_admin', 'إدارات مركزية')], max_length=15)),
                ('addressed_to_type', models.CharField(choices=[('dean', 'العميد شخصياً'), ('faculty', 'الكلية (شخص محدد)')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='correspondence_files/')),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('uploaded', 'مرفوع'), ('pending_dean', 'قيد المراجعة عند العميد/نائبه'), ('assigned', 'موجه'), ('archived', 'منفذ / مؤرشف')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_correspondences', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_correspondences', to=settings.AUTH_USER_MODEL)),
                ('recipient_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_correspondences', to=settings.AUTH_USER_MODEL)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='correspondence.correspondence')),
                ('sender_internal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_correspondences', to=settings.AUTH_USER_MODEL)),
                ('recipient_external', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_correspondences', to='correspondence.externalentity')),
                ('sender_external', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_correspondences', to='correspondence.externalentity')),
            ],
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_directives', to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='correspondence.correspondence')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_directives', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('secretary', 'سكرتير'), ('dean', 'عميد'), ('vice_dean', 'نائب عميد'), ('registrar', 'مسجل'), ('department_head', 'رئيس قسم'), ('admin_supervisor', 'مشرف إداري'), ('faculty_member', 'أستاذ/أستاذة')], default='faculty_member', max_length=30)),
                ('department', models.CharField(blank=True, choices=[('cs', 'علوم الحاسوب'), ('it', 'تقانة المعلومات'), ('is', 'نظم المعلومات')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
