# Generated by Django 5.2.15 on 2026-06-30 06:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondence',
            options={'verbose_name': 'مراسلة / خطاب', 'verbose_name_plural': 'الخطابات والمراسلات'},
        ),
        migrations.AlterModelOptions(
            name='directive',
            options={'verbose_name': 'توجيه رقمي', 'verbose_name_plural': 'التوجيهات الرقمية'},
        ),
        migrations.AlterModelOptions(
            name='externalentity',
            options={'verbose_name': 'جهة خارجية', 'verbose_name_plural': 'الجهات الخارجية'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'ملفات المستخدمين الشخصية'},
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='addressed_to_type',
            field=models.CharField(choices=[('dean', 'العميد شخصياً'), ('faculty', 'الكلية (شخص محدد)')], max_length=10, verbose_name='المخاطب الفعلي'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء في النظام'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_correspondences', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='direction',
            field=models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=15, verbose_name='الاتجاه'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='document_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ الخطاب'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='file',
            field=models.FileField(upload_to='correspondence_files/', verbose_name='ملف الخطاب (PDF)'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_correspondences', to=settings.AUTH_USER_MODEL, verbose_name='تمت معالجته بواسطة'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='recipient_external',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_correspondences', to='correspondence.externalentity', verbose_name='المستلم الخارجي'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='recipient_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_correspondences', to=settings.AUTH_USER_MODEL, verbose_name='المستلم الداخلي'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='الرقم المرجعي'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='correspondence.correspondence', verbose_name='مرتبط بخطاب سابق (رد)'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='scope',
            field=models.CharField(choices=[('internal', 'داخلي'), ('inter_faculty', 'بين الكليات'), ('central_admin', 'إدارات مركزية')], max_length=15, verbose_name='النطاق'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='sender_external',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_correspondences', to='correspondence.externalentity', verbose_name='المرسل الخارجي'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='sender_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_correspondences', to=settings.AUTH_USER_MODEL, verbose_name='المرسل الداخلي'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='status',
            field=models.CharField(choices=[('uploaded', 'مرفوع'), ('pending_dean', 'قيد المراجعة عند العميد/نائبه'), ('assigned', 'موجه'), ('archived', 'منفذ / مؤرشف')], default='uploaded', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='عنوان الخطاب / الموضوع'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_directives', to=settings.AUTH_USER_MODEL, verbose_name='موجه إلى (الموظف المستهدف)'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='correspondence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='correspondence.correspondence', verbose_name='الخطاب المرتبط'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ صدور التوجيه'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='directive_text',
            field=models.TextField(verbose_name='نص التوجيه الرقمي'),
        ),
        migrations.AlterField(
            model_name='directive',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_directives', to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة (العميد/النائب)'),
        ),
        migrations.AlterField(
            model_name='externalentity',
            name='category',
            field=models.CharField(choices=[('other_faculty', 'كلية أخرى'), ('central_admin', 'إدارة مركزية')], max_length=20, verbose_name='تصنيف الجهة'),
        ),
        migrations.AlterField(
            model_name='externalentity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الجهة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('cs', 'علوم الحاسوب'), ('it', 'تقانة المعلومات'), ('is', 'نظم المعلومات')], max_length=10, null=True, verbose_name='القسم الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('secretary', 'سكرتير'), ('dean', 'عميد'), ('vice_dean', 'نائب عميد'), ('registrar', 'مسجل'), ('department_head', 'رئيس قسم'), ('admin_supervisor', 'مشرف إداري'), ('faculty_member', 'أستاذ/أستاذة')], default='faculty_member', max_length=30, verbose_name='الدور / الوظيفة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
