# Generated by Django 5.2.15 on 2026-07-01 03:35

import correspondence.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_alter_correspondence_options_alter_directive_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='file',
            field=models.FileField(upload_to='correspondence_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), correspondence.models.validate_file_size], verbose_name='ملف الخطاب (PDF)'),
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=15)),
                ('scope', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('direction', 'scope', 'year')},
            },
        ),
    ]
