# Generated by Django 5.2.15 on 2026-07-24 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_seed_reference_counters'),  # يعتمد على الهجرة السابقة للعدادات
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='correspondence.correspondence', verbose_name='الخطاب المرتبط')),
            ],
            options={
                'verbose_name': 'تعليق داخلي',
                'verbose_name_plural': 'التعليقات الداخلية',
            },
        ),
    ]
