# Generated by Django 5.2.15 on 2026-07-01 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_seed_reference_counters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='directive',
            constraint=models.UniqueConstraint(fields=('correspondence',), name='one_directive_per_correspondence'),
        ),
    ]
